/**
 * Regenerate PROGRESS.md from the PAUL files.
 *
 * Derived, not hand-written, so it cannot drift from reality:
 *   .paul/progress.json  feature inventory + status (the one file to edit)
 *   .paul/ROADMAP.md     plan checkboxes per phase
 *   .paul/paul.toml      milestone / phase / loop position
 *
 * Run: npm run progress
 */

const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.resolve(__dirname, '..');
const read = (p) => fs.readFileSync(path.join(ROOT, p), 'utf8');

const STATUS = {
  done: { icon: '✅', label: 'Done', credit: 1 },
  partial: { icon: '🟡', label: 'Partial', credit: 0.5 },
  blocked: { icon: '⛔', label: 'Blocked', credit: 0 },
  todo: { icon: '⬜', label: 'Not started', credit: 0 },
};

function bar(pct, width = 20) {
  const filled = Math.round((pct / 100) * width);
  return '█'.repeat(filled) + '░'.repeat(width - filled);
}

// --- inputs --------------------------------------------------------------------

const data = JSON.parse(read('.paul/progress.json'));

// Normalise line endings: these files are edited on Windows and CRLF silently
// breaks any regex that anchors on \n.
const readLF = (p) => read(p).replace(/\r\n/g, '\n');

let toml = '';
try {
  toml = readLF('.paul/paul.toml');
} catch {
  /* optional */
}

/** Value of `key` inside the `[section]` table. */
const tomlIn = (section, key) => {
  const block = toml.split(/^\[/m).find((b) => b.startsWith(section + ']'));
  if (!block) return null;
  const m = block.match(new RegExp('^' + key + ' = "([^"]*)"', 'm'));
  return m ? m[1] : null;
};

let roadmap = '';
try {
  roadmap = readLF('.paul/ROADMAP.md');
} catch {
  /* optional */
}

// Plan checkboxes, e.g. "- [x] 01-01: ..."
const planLines = [...roadmap.matchAll(/^- \[([ x])\] (\d{2}-\d{2}): (.+)$/gm)].map((m) => ({
  done: m[1] === 'x',
  id: m[2],
  text: m[3].replace(/\s+—\s+_complete.*$/, '').trim(),
}));

// --- feature maths -------------------------------------------------------------

const feats = data.features;
const totalWeight = feats.reduce((a, f) => a + f.weight, 0);
const earned = feats.reduce((a, f) => a + f.weight * (STATUS[f.status]?.credit ?? 0), 0);
const featurePct = totalWeight ? Math.round((earned / totalWeight) * 100) : 0;

// Blocked weight is worth calling out separately: it is not "remaining work" in the
// ordinary sense, because a known obstacle stands in front of it.
const blockedWeight = feats
  .filter((f) => f.status === 'blocked')
  .reduce((a, f) => a + f.weight, 0);

const foundation = data.foundation || [];
const foundationDone = foundation.filter((f) => f.status === 'done').length;

const plansDone = planLines.filter((p) => p.done).length;
const planPct = planLines.length ? Math.round((plansDone / planLines.length) * 100) : 0;

// --- render --------------------------------------------------------------------

const groups = [...new Set(feats.map((f) => f.group))];
// Local date, not UTC: the report is read next to the user's own clock, and an
// hour's offset made it look a day stale.
const today = new Date().toLocaleDateString('en-CA');

let out = `# Progress

_Generated by \`npm run progress\` — do not edit by hand. Edit \`.paul/progress.json\` instead._
_Last generated: ${today}_

## Overall

**${featurePct}% of declared features**, by effort weight.

\`\`\`
${bar(featurePct)} ${featurePct}%
\`\`\`

| Measure | Value |
| --- | --- |
| Feature completion (weighted) | ${featurePct}% — ${earned} of ${totalWeight} points |
| Plans completed | ${plansDone} of ${planLines.length} defined (${planPct}%) |
| Foundation items done | ${foundationDone} of ${foundation.length} |
| Current milestone | ${tomlIn('milestone', 'name') || '—'} |
| Current phase | ${tomlIn('phase', 'name') || '—'} (${tomlIn('phase', 'status') || '—'}) |
| Loop position | ${tomlIn('loop', 'position') || '—'} |

> **What this percentage does and does not mean.** It measures the core features declared in
> \`.paul/PROJECT.md\`, weighted by rough effort. It is **not** a schedule estimate, and it does not
> cover work nobody has declared yet. Items still to build are counted in the denominator, so this
> reflects the product as now intended rather than as first declared. Treat it as "how much of the
> intended product exists", not "how close to done".
`;

if (blockedWeight > 0) {
  out += `
> ⛔ **${Math.round((blockedWeight / totalWeight) * 100)}% of the remaining weight is blocked**, not merely unstarted. See the blocked rows below.
`;
}

out += `
## Features

`;

for (const g of groups) {
  const rows = feats.filter((f) => f.group === g);
  const gTotal = rows.reduce((a, f) => a + f.weight, 0);
  const gEarned = rows.reduce((a, f) => a + f.weight * (STATUS[f.status]?.credit ?? 0), 0);
  const gPct = gTotal ? Math.round((gEarned / gTotal) * 100) : 0;
  out += `### ${g} — ${gPct}%\n\n`;
  out += `| | Feature | Status | Shipped in | Note |\n| --- | --- | --- | --- | --- |\n`;
  for (const f of rows) {
    const st = STATUS[f.status] || STATUS.todo;
    out += `| ${st.icon} | ${f.name} | ${st.label} | ${f.shipped || '—'} | ${f.note || ''} |\n`;
  }
  out += '\n';
}

out += `## Plans

| | Plan | Description |
| --- | --- | --- |
`;
for (const p of planLines) {
  out += `| ${p.done ? '✅' : '⬜'} | ${p.id} | ${p.text} |\n`;
}

out += `
## Foundation

Infrastructure that carries features but ships none by itself. Excluded from the headline
percentage deliberately — otherwise plumbing inflates the number while the product stays unusable.

| | Item | Shipped in |
| --- | --- | --- |
`;
for (const f of foundation) {
  out += `| ${f.status === 'done' ? '✅' : '⬜'} | ${f.name} | ${f.shipped || '—'} |\n`;
}

out += `
---

_Update \`.paul/progress.json\` when a plan ships a feature, then run \`npm run progress\`._
`;

fs.writeFileSync(path.join(ROOT, 'PROGRESS.md'), out);
console.log(
  `PROGRESS.md written — ${featurePct}% features (${earned}/${totalWeight}), ${plansDone}/${planLines.length} plans`,
);
